permissions:
  contents: read
  issues: write
  pull-requests: write
name: Canonical Guard

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  canonical-guard:
    uses: SPECTRADataSolutions/.github/.github/workflows/reusable-canonical-guard.yml@main