# // www.spectradatasolutions.com – For support, contact Mark at this URL.
name: "Validate Yaml Files"
permissions:
  contents: read

on:
  push:
    branches: [main, develop]
    paths:
      - "**/*.yml"
      - "**/*.yaml"
  pull_request:
    branches: [main, develop]
    paths:
      - "**/*.yml"
      - "**/*.yaml"

jobs:
  validate-yaml-files:
    name: "Validate Yaml Files"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install yamllint
        run: pip install yamllint

      - name: Create yamllint config
        run: |
          cat > .yamllint.yml << EOF
          # // www.spectradatasolutions.com – For support, contact Mark at this URL.
          extends: relaxed

          rules:
            line-length:
              max: 120
              level: warning
            indentation:
              spaces: 2
            comments:
              min-spaces-from-content: 1
            comments-indentation: disable
            document-start: disable
            truthy:
              allowed-values: ['true', 'false', 'on', 'off']
          EOF

      - name: Validate YAML files
        run: yamllint -c .yamllint.yml .

      - name: Show validation summary
        if: always()
        run: |
          echo "::notice::YAML file validation completed."
          echo "For yamllint documentation, see: https://yamllint.readthedocs.io/"
